### ISSUE TITLE
BadValue for X when using arrow keys

### ISSUE THREAD

**Issue by pevogam** [autopilot-rs/autopy#10] opened 2018-06-16 06:57 UTC
The arrow keys have problems (tested on Fedora 27 platforms), resulting in fatal errors like:

    X Error of failed request:  BadValue (integer parameter out of range for operation)
      Major opcode of failed request:  132 (XTEST)
      Minor opcode of failed request:  2 (X_XTestFakeInput)
      Value in failed request:  0x0
      Serial number of failed request:  14
      Current serial number in output stream:  15

Some minimal code to reproduce the issue above:

    from autopy import key as k
    k.tap(k.Code.DOWN_ARROW, [])

The same happens for any other arrow key, haven't tested for more but works for a key like RETURN. I hope I am using the `key` module correctly and the above error is fatal in the sense that it interrupts unit tests and any python session where it would run.

**Comment by nicolasmiller** [comment] 2018-06-20 22:07
Ran into the same issue. Think I found the cause. Opened a PR against the parent Rust project here: https://github.com/autopilot-rs/autopilot-rs/pull/11

**Comment by msanders** [comment] 2018-09-02 22:16
Fixed on latest master.

**Closed by msanders** 2018-09-02 22:16 UTC
